- README.md
- Clarified how to submit feature requests
- Clarified how to submit product issues
- Added link to Contribution guidelines
> chore: added additional links

- README.md
> Added OPA implementation

- README.md
> chore: add link to roadmap

- README.md
Cross-linking to the GOVERNANCE.md file.
> Add governance heading

- ADOPTERS.MD
added mapped.com as an adopter of openfga
> [ADOPTER] mapped.com

- README.md
> chore: add a link to the community meetings

- ADOPTERS.MD
> Add Procure Ai to ADOPTERS.md

- ADOPTERS.MD
Adding Canonical to the adopters list
Adding Canonical to the adopters list
> Update ADOPTERS.MD to add Canonical

- ADOPTERS.md
I added my workplace in the ADOPTERS.md list.
> docs: add Italarchivi to ADOPTERS.md

- ADOPTERS.md
Add Virtool to the adopters list.
Add Virtool to the adopters list.
> Add Virtool to adopters

- ADOPTERS.md
Add [Configu](https://configu.com) to the adopters list. We will soon publish an article about how we used OpenFGA to implement our authorization system ⭐
> Add Configu to adopters

- community-meetings.md
Previously this was linking to the April 2023 meeting as part of the YouTube playlist.
> docs: Link to Community Meeting playlist

- ADOPTERS.md
Add ExcID to adopters
ExcID uses OpenFGA for its digital twins access control solution https://medium.com/@excid/relation-based-access-control-using-verifiable-credentials-d8e542a0ce1
> Add ExcID to adopters

- ADOPTERS.md
We're using it for our OSS project called Minder.
> Add Stacklok as adopter of OpenFGA

- ADOPTERS.md
Renaming Auth0 FGA to Okta FGA
> Rename Auth0 FGA to Okta FGA in Adopters

- ADOPTERS.md
Adding [Moss](https://getmoss.com/) as adopter.
#References
> add Moss to ADOPTERS.md

- ADOPTERS.md
Added links to articles that explain how users implemented OpenFGA
> feat: added link to articles

- ADOPTERS.md
Updating ADOPTERS.md to add Agicap as requested by Andres :)
> docs: adding Agicap as adopter in ADOPTERS.md

- ADOPTERS.md
> chore: remoe extra whitespace from ADOPTERS.md

- README.md
> chore: added testcontainers for Java

- ADOPTERS.md
Adds Instill AI to ADOPTERS.md
> docs: add Instill AI to ADOPTERS.md

- ADOPTERS.md
> docs: add Zuplo to Adopters

- ADOPTERS.md
> docs: add openobserve to Adopters

- related-projects.md
> feat: add related projects document

- community-meetings.md
> chore: update community meetings with more time zone info

- ADOPTERS.md
Adds Datum to adoptoers list
library wrapper: https://github.com/datumforge/fgax
> docs: add Datum to Adopters

- README.md
> chore: add more community projects

- ADOPTERS.md
Hi, thanks for a great software!
We have built our IAM framework based on OpenFGA for our services.
See https://sourcegraph.notion.site/MSP-IAM-framework-01f6e471a62245968453bfcb2cf052a3
> ADOPTERS: add Sourcegraph

- ADOPTERS.md
> Add Docker in adopters list

- ADOPTERS.md
> docs: add Bump to Adopters

- ADOPTERS.md
> Adjusted adopters.md to add consulting firms

- ADOPTERS.md
Adds Kilterset as an implementation partner.
> Add Kilterset as an implementation partner to ADOPTERS.md

- ADOPTERS.md
Amend `ADOPTERS.md` with Kilterset contact link.
> Adopters: Add contact link for Kilterset

- ADOPTERS.md
The primary goal of this update is to provide organizations with a comprehensive list of companies that can assist with implementing OpenFGA. By including Mrikal, we aim to enhance the resources available to users and support the wider adoption of OpenFGA solutions.
> Update OpenFGA Implementation Service Providers List with Mrikal

- ADOPTERS.md
If you require further information please get in touch with kaan.kahraman@patikaglobal.com and kursat.coskun@patikaglobal.com
> Added Patika Global Technology to Adopters.

- ADOPTERS.md
Update to ADOPTERS.md to add a section for those using OpenFGA in production to provide details on their use case.
- [X ] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ -] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [X ] The correct base branch is being used, if not `main`
- [ -] I have added tests to validate that the change in functionality is working as expected
> feat: add adopters use case

- ADOPTERS.md
Added use case description in Adopters list (#358)
> docs: add ProcureAi use case to adopters list (#358)

- ADOPTERS.md
> feat: add Bump adopter description

- ADOPTERS.md
Requested by https://github.com/openfga/community/issues/358
> docs: update Sourcegraph use case

- ADOPTERS.md
This code was moved to our OpenLane organization, added usage as requested.
Update to OpenLane, add usage information
adds usage information 
n/a
> Update Adopters for OpenLane

- README.md
Added link to Kubernetes Operator
> Added link to fga-operator community project

- ADOPTERS.md
This adds [Gilion](https://www.gilion.com/) as adopters of OpenFGA.
If you haven't done so yet, we would appreciate it if you could star the [OpenFGA repository](https://github.com/openfga/openfga). :)
> Add Gilion (https://gilion.com/) as adopters

- ADOPTERS.md
Adds [flex](https://flex.team) to adopter list
If you haven't done so yet, we would appreciate it if you could star the [OpenFGA repository](https://github.com/openfga/openfga). :)
> docs: add flex usecase to adopters list

- ADOPTERS.md
Updates the status of Minder, which was donated to the OpenSSF.
> Update Minder status after foundation donation

- ADOPTERS.md
Adopters table updated to include ExcID use case description
Adopters table updated to include ExcID use case description
- [ X] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ X] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [ X] The correct base branch is being used, if not `main`
- [ X] I have added tests to validate that the change in functionality is working as expected
> chore: update ExcID with use-case

- README.md
This PR adds [a community PHP SDK](https://github.com/evansims/openfga-php) for OpenFGA to the README.
N/A
> docs(README): add PHP SDK link

- ADOPTERS.md
We are now productive with OpenFGA under the hood. We are using Rust, fully automate Authorization Model management, and best of all, it's all open-source. Maybe our repo can inspire others trying to achieve the same.
Probably the bottom of the list is the place to go? :D
Lakekeeper -> Adopters.md
> chore(adopters): Add Lakekeeper as adopter

- README.md
Added a section for API Gateways that includes Kong
> Added a section for API Gateways that includes Kong

- README.md
We have a new github organization and the old link is dead, updating to the update location.
Updating the Openlane extensions link
Updates the link to the new organization
> fix: update README.md - Openlane Extensions

- ADOPTERS.md
* adds Skyral to the list of adopters of OpenFGA
> chore: add skyral to adopters list

- README.md
Adding links to examples/videos
> Add links to intro articles + videos

- ADOPTERS.md
> Add AppsCode to ADOPTERS list

- ADOPTERS.md
Add Grafana Labs to ADOPTERS.md
> Add Grafana Labs to ADOPTERS.md

- ADOPTERS.md
> Add EarthScope to ADOPTERS.md

- ADOPTERS.md
Add Incus to the list of OpenFGA adopters.
> ADOPTERS: Add Incus

- ADOPTERS.md
This PR updates the ADOPTERS.md to add X-HR LABS to Companies/Projects using OpenFGA in production
- [ x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [ x] The correct base branch is being used, if not `main`
> Adding additional adopter to the list - X-HR LABS

- README.md
This PR updates the README with links to the community-maintained [OpenFGA Laravel SDK](https://github.com/evansims/openfga-laravel/) and [OpenFGA MCP (Model Context Protocol) server](https://github.com/evansims/openfga-mcp/).
> docs(README): add Laravel and MCP

- README.md
Add section for IDEs/Editor integrations
> chore: Add IDE or Editors integrations section
